[package]
name = "ad-clicker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.43", features = ["derive"] }
futures = "0.3.31"
thirtyfour = { version = "0.36.1", features = ["tokio-multi-threaded"] }
tokio = { version = "1.47.1", features = ["full"] }
